# version: 2
# updates:
# - package-ecosystem: pip
#   directory: "/"
#   schedule:
#     interval: daily
#     time: "08:00"
#   open-pull-requests-limit: 99
#   ignore:
#   - dependency-name: setuptools
#     versions:
#     - 52.0.0
#     - 53.0.0
#     - 53.1.0
#     - 54.0.0
#     - 54.1.1
#     - 54.1.2
#     - 54.2.0
#   - dependency-name: pip
#     versions:
#     - "21.0"
#     - 21.0.1
